//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int client_id { get; set; }
        public Nullable<int> worker_id { get; set; }
        public int technic_id { get; set; }
        public int problem_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> days { get; set; }
        public string comment { get; set; }
    
        public virtual problem problem { get; set; }
        public virtual status status { get; set; }
        public virtual technic technic { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
