//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoServiceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechnoserviceEntities : DbContext
    {
        private static TechnoserviceEntities context;
        public TechnoserviceEntities()
            : base("name=TechnoserviceEntities")
        {
        }
        public static TechnoserviceEntities GetEntities()
        {
            if (context == null)
            {
                context = new TechnoserviceEntities();
            }
            return context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<problem> problem { get; set; }
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<technic> technic { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
